
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: maleb
  password: 
  host: localhost
 

development:
  <<: *default
  database: elimisha

test:
  <<: *default
  database: elimisha

production:
  <<: *default
  database: elimisha
